# Generated by Django 4.2.3 on 2023-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_task_if_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('chat_room_id', models.IntegerField()),
                ('if_done', models.BooleanField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
