# Generated by Django 4.2.3 on 2023-09-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
